// 完整词库数据（从 index.html 迁移）
export const wordDatabase = {
  easy: [
    'cat', 'dog', 'sun', 'moon', 'tree', 'fish', 'bird', 'star', 'love', 'hope',
    'car', 'book', 'hand', 'eye', 'sea', 'sky', 'ice', 'fire', 'rock', 'wind',
    'home', 'time', 'day', 'night', 'light', 'dark', 'food', 'water', 'blue',
    'red', 'green', 'white', 'black', 'big', 'small', 'good', 'bad', 'new',
    'old', 'fast', 'slow', 'happy', 'sad', 'cold', 'hot', 'yes', 'no', 'up',
    'down', 'left', 'right', 'open', 'close', 'run', 'walk', 'jump', 'fly',
    'swim', 'eat', 'drink', 'sleep', 'play', 'work', 'help', 'find', 'make',
    'take', 'give', 'come', 'go', 'see', 'hear', 'feel', 'think', 'know',
    'say', 'tell', 'read', 'write', 'learn', 'teach', 'sing', 'dance', 'smile',
    'boy', 'girl', 'man', 'woman', 'baby', 'child', 'mom', 'dad', 'friend', 'name',
    'face', 'head', 'hair', 'nose', 'mouth', 'foot', 'leg', 'arm', 'back', 'side',
    'house', 'room', 'door', 'wall', 'floor', 'chair', 'table', 'bed', 'box', 'bag',
    'hat', 'coat', 'dress', 'shoe', 'sock', 'shirt', 'pants', 'ring', 'watch', 'key',
    'pen', 'paper', 'phone', 'toy', 'game', 'ball', 'bike', 'train', 'plane', 'boat',
    'apple', 'cake', 'bread', 'milk', 'tea', 'soup', 'meat', 'fish', 'egg', 'rice',
    'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten',
    'first', 'last', 'next', 'best', 'long', 'short', 'high', 'low', 'far', 'near',
    'warm', 'cool', 'dry', 'wet', 'clean', 'dirty', 'full', 'empty', 'loud', 'quiet',
    'easy', 'hard', 'safe', 'free', 'busy', 'ready', 'sure', 'real', 'true', 'wrong',
    'Cat', 'Dog', 'Sun', 'Moon', 'Tree', 'Fish', 'Bird', 'Star', 'Love', 'Hope',
    'Car', 'Book', 'Hand', 'Eye', 'Sea', 'Sky', 'Ice', 'Fire', 'Rock', 'Wind',
    'Home', 'Time', 'Day', 'Night', 'Light', 'Dark', 'Food', 'Water', 'Blue',
    'Red', 'Green', 'White', 'Black', 'Big', 'Small', 'Good', 'Bad', 'New',
    'Old', 'Fast', 'Slow', 'Happy', 'Sad', 'Cold', 'Hot', 'Yes', 'No', 'Up',
    'Down', 'Left', 'Right', 'Open', 'Close', 'Run', 'Walk', 'Jump', 'Fly'
  ],
  medium: [
    'computer', 'keyboard', 'rainbow', 'mountain', 'elephant', 'butterfly', 'adventure', 'creativity',
    'orange', 'flower', 'window', 'summer', 'winter', 'spring', 'autumn', 'nature',
    'picture', 'music', 'artist', 'science', 'history', 'culture', 'freedom', 'justice',
    'wisdom', 'courage', 'friendship', 'journey', 'discovery', 'miracle', 'mystery', 'energy',
    'future', 'memory', 'dream', 'vision', 'success', 'challenge', 'victory', 'progress',
    'balance', 'harmony', 'passion', 'strength', 'beauty', 'wonder', 'magic', 'secret',
    'treasure', 'kingdom', 'legend', 'story', 'chapter', 'golden', 'silver', 'crystal',
    'diamond', 'emerald', 'ocean', 'forest', 'desert', 'valley', 'river', 'waterfall',
    'sunset', 'sunrise', 'shadow', 'reflection', 'universe', 'galaxy', 'planet', 'comet',
    'thunder', 'lightning', 'earthquake', 'volcano', 'hurricane', 'tornado', 'blizzard',
    'technology', 'education', 'knowledge', 'language', 'sentence', 'paragraph', 'library', 'museum',
    'hospital', 'restaurant', 'factory', 'office', 'building', 'bridge', 'tunnel', 'station',
    'airport', 'highway', 'traffic', 'vehicle', 'motorcycle', 'bicycle', 'helicopter', 'submarine',
    'telephone', 'television', 'camera', 'calculator', 'refrigerator', 'microwave', 'washing', 'machine',
    'furniture', 'curtain', 'carpet', 'mirror', 'painting', 'sculpture', 'pottery', 'jewelry',
    'birthday', 'holiday', 'vacation', 'festival', 'ceremony', 'celebration', 'party', 'wedding',
    'morning', 'afternoon', 'evening', 'midnight', 'yesterday', 'today', 'tomorrow', 'weekend',
    'january', 'february', 'march', 'april', 'may', 'june', 'july', 'august',
    'september', 'october', 'november', 'december', 'monday', 'tuesday', 'wednesday', 'thursday',
    'friday', 'saturday', 'sunday', 'calendar', 'schedule', 'appointment', 'meeting', 'conference',
    'baseball', 'basketball', 'football', 'tennis', 'swimming', 'running', 'climbing', 'skiing',
    'cooking', 'baking', 'gardening', 'painting', 'drawing', 'writing', 'reading', 'studying',
    'shopping', 'traveling', 'exploring', 'hiking', 'camping', 'fishing', 'hunting', 'sailing',
    'medicine', 'surgery', 'treatment', 'therapy', 'exercise', 'nutrition', 'healthy', 'fitness',
    'Computer', 'Keyboard', 'Rainbow', 'Mountain', 'Elephant', 'Butterfly', 'Adventure', 'Creativity',
    'Orange', 'Flower', 'Window', 'Summer', 'Winter', 'Spring', 'Autumn', 'Nature',
    'Picture', 'Music', 'Artist', 'Science', 'History', 'Culture', 'Freedom', 'Justice',
    'Wisdom', 'Courage', 'Friendship', 'Journey', 'Discovery', 'Miracle', 'Mystery', 'Energy',
    'Future', 'Memory', 'Dream', 'Vision', 'Success', 'Challenge', 'Victory', 'Progress',
    'Balance', 'Harmony', 'Passion', 'Strength', 'Beauty', 'Wonder', 'Magic', 'Secret',
    'Technology', 'Education', 'Knowledge', 'Language', 'Sentence', 'Paragraph', 'Library', 'Museum',
    'Hospital', 'Restaurant', 'Factory', 'Office', 'Building', 'Bridge', 'Tunnel', 'Station',
    'Airport', 'Highway', 'Traffic', 'Vehicle', 'Motorcycle', 'Bicycle', 'Helicopter', 'Submarine',
    'Birthday', 'Holiday', 'Vacation', 'Festival', 'Ceremony', 'Celebration', 'Party', 'Wedding',
    'Morning', 'Afternoon', 'Evening', 'Midnight', 'Yesterday', 'Today', 'Tomorrow', 'Weekend'
  ],
  hard: [
    'programming', 'typography', 'photography', 'architecture', 'responsibility', 'extraordinary',
    'magnificent', 'development', 'performance', 'experience', 'achievement', 'accomplishment',
    'investigation', 'communication', 'transformation', 'revolutionary', 'technological', 'sophisticated',
    'philosophical', 'psychological', 'environmental', 'international', 'professional', 'educational',
    'organizational', 'constitutional', 'experimental', 'theoretical', 'mathematical', 'geographical',
    'astronomical', 'archaeological', 'anthropological', 'meteorological', 'biological', 'sociological',
    'infrastructure', 'sustainability', 'biodiversity', 'cryptocurrency', 'artificial', 'intelligence',
    'algorithm', 'encryption', 'cybersecurity', 'blockchain', 'quantum', 'mechanics', 'relativity', 'evolution',
    'genetics', 'biotechnology', 'nanotechnology', 'renewable', 'sustainable', 'optimization', 'configuration', 'implementation',
    'compatibility', 'functionality', 'accessibility', 'availability', 'reliability', 'scalability',
    'flexibility', 'versatility', 'efficiency', 'productivity', 'creativity', 'innovation',
    'collaboration', 'coordination', 'synchronization', 'standardization', 'globalization', 'digitalization',
    'extraordinary', 'incomprehensible', 'revolutionary', 'unprecedented', 'sophisticated', 'comprehensive',
    'characterization', 'representation', 'interpretation', 'administration', 'recommendation', 'demonstration',
    'differentiation', 'personalization', 'specialization', 'generalization', 'categorization', 'industrialization',
    'commercialization', 'internationalization', 'decentralization', 'democratization', 'modernization',
    'electromagnetic', 'thermodynamic', 'aerodynamic', 'hydrodynamic', 'biochemical', 'geochemical',
    'neurological', 'cardiological', 'dermatological', 'ophthalmological', 'otolaryngological', 'gastroenterological',
    'microprocessor', 'supercomputer', 'semiconductor', 'microcontroller', 'telecommunication', 'radiofrequency',
    'multidimensional', 'interdisciplinary', 'multifunctional', 'interconnected', 'interchangeable', 'entrepreneurial',
    'philanthropic', 'humanitarian', 'computational', 'informational',
    'Programming', 'Typography', 'Photography', 'Architecture', 'Responsibility', 'Extraordinary',
    'Magnificent', 'Development', 'Performance', 'Experience', 'Achievement', 'Accomplishment',
    'Investigation', 'Communication', 'Transformation', 'Revolutionary', 'Technological', 'Sophisticated',
    'Philosophical', 'Psychological', 'Environmental', 'International', 'Professional', 'Educational',
    'Organizational', 'Constitutional', 'Experimental', 'Theoretical', 'Mathematical', 'Geographical',
    'Astronomical', 'Archaeological', 'Anthropological', 'Meteorological', 'Biological', 'Sociological',
    'Infrastructure', 'Sustainability', 'Biodiversity', 'Cryptocurrency', 'Artificial', 'Intelligence',
    'Algorithm', 'Encryption', 'Cybersecurity', 'Blockchain', 'Quantum', 'Mechanics',
    'Nanotechnology', 'Renewable', 'Sustainable', 'Optimization', 'Configuration', 'Implementation',
    'Compatibility', 'Functionality', 'Accessibility', 'Availability', 'Reliability', 'Scalability',
    'Entrepreneurial', 'Philanthropic', 'Humanitarian', 'Environmental', 'Computational', 'Informational'
  ]
};

// 同步到全局，确保遗留脚本仍可使用
if (typeof window !== 'undefined') {
  window.wordDatabase = wordDatabase;
}

// 方便调试：暴露桥接
if (typeof window !== 'undefined') {
  window.wordDatabaseBridge = wordDatabase;
} 